### ISSUE TITLE
CLI breaks during packager definition step

### ISSUE THREAD

**Issue by Yurickh** [Yurickh/ouxe#5]
```
TypeError: Cannot destructure property 'name' of 'packagerConfig[manager]' as it is undefined.
    at packageManager (/Users/yurick/github/oss/ouxe/src/helpers/package-manager.ts:37:11)
    at installDependencies (/Users/yurick/github/oss/ouxe/src/helpers/install-dependencies.ts:29:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.handler (/Users/yurick/github/oss/ouxe/src/commands/prettier/index.ts:38:20)
    at Object.routeFeatures [as handler] (/Users/yurick/github/oss/ouxe/src/index.ts:21:5)
```

**Comment by Yurickh** [comment]
Fixed by 7799b6a
